Parameters:
  BucketName:
    Type: String
Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "${BucketName}"
      AccessControl: Private
Outputs:
  BucketArn:
    Value: !GetAtt Bucket.Arn